# fly.toml app configuration file generated for fazztrack-backend on 2025-07-10T12:05:43-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fazztrack-backend'
primary_region = 'iad'

[build]

[deploy]
  strategy = 'immediate'

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[processes]
  app = 'dumb-init node dist/main'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
